. | select(
 (.["bibliography"] == "")
 or (.["breeding"] == "")
 or (.["taxonomy"] == "")
 or (.["taxonomy"] == "")
 or (.["commonNames"] == "")
 or (.["descriptiveNotes"] == "")
 or (.["habitat"] == "")
 or (.["foodAndFeeding"] == "")
 or (.["activityPatterns"] == "")
 or (.["movementsHomeRangeAndSocialOrganization"] == "")
 or (.["statusAndConservation"] == "")
 or (.["distributionImageURL"] == "")
)
